"use client";
import Link from "next/link";
import { ArrowLeft, ExternalLink, Send } from "lucide-react";
import { useEffect, useState } from "react";
import { createPublicClient, createWalletClient, custom, decodeEventLog, defineChain, http, keccak256, parseEther, toBytes } from "viem";
import { readJobs, updateJob, type GatewayJob } from "@/lib/jobs";
import { ProgressRail } from "./shared/progress-rail";
import { StatusBadge } from "./shared/status-badge";
import { ToastRegion } from "./shared/toast-region";

type Config = { agentEscrow: string | null; gatewayRouter: string | null; requestFeeEth: string; baseRpcUrl: string };
const chain = defineChain({ id: 84532, name: "Base Sepolia", nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 }, rpcUrls: { default: { http: ["https://sepolia.base.org"] } }, testnet: true });
const abi = [
  { type: "function", name: "submitEvidence", stateMutability: "nonpayable", inputs: [{ name: "jobId", type: "uint256" }, { name: "evidenceUri", type: "string" }, { name: "evidenceHash", type: "bytes32" }], outputs: [] },
  { type: "function", name: "requestVerification", stateMutability: "payable", inputs: [{ name: "jobId", type: "uint256" }, { name: "question", type: "string" }, { name: "policy", type: "string" }, { name: "expiry", type: "uint64" }], outputs: [{ name: "requestId", type: "bytes32" }] },
  { type: "event", name: "RequestDispatched", anonymous: false, inputs: [{ name: "requestId", type: "bytes32", indexed: true }, { name: "messageId", type: "bytes32", indexed: true }, { name: "requester", type: "address", indexed: true }, { name: "originContract", type: "address", indexed: false }, { name: "callback", type: "address", indexed: false }, { name: "questionHash", type: "bytes32", indexed: false }, { name: "policyHash", type: "bytes32", indexed: false }, { name: "evidenceHash", type: "bytes32", indexed: false }] },
] as const;
const routerAbi = [{ type: "function", name: "requests", stateMutability: "view", inputs: [{ name: "requestId", type: "bytes32" }], outputs: [{ name: "requester", type: "address" }, { name: "originContract", type: "address" }, { name: "callback", type: "address" }, { name: "nonce", type: "uint64" }, { name: "expiry", type: "uint64" }] }] as const;

export function JobDetail({ id, config }: { id: string; config: Config }) {
  const [job, setJob] = useState<GatewayJob | null>(null); const [uri, setUri] = useState(""); const [hash, setHash] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { const found = readJobs().find((item) => item.id === id || item.onChainJobId === id) ?? null; setJob(found); if (found?.evidenceUri) setUri(found.evidenceUri); if (found?.evidenceHash) setHash(found.evidenceHash); }, [id]);
  useEffect(() => { if (!job?.requestId) return; let active = true; const refresh = async () => { const response = await fetch(`/api/v1/requests/${job.requestId}`).catch(() => null); if (!response?.ok || !active) return; const record = await response.json(); const nextStatus = record.status === "CALLBACK_EXECUTED" && record.result?.decision === "PASS" ? "COMPLETED" : record.status === "CALLBACK_EXECUTED" && record.result?.decision === "FAIL" ? "REFUNDED" : record.status === "REQUIRES_REVIEW" ? "REVIEW_REQUIRED" : "IN_REVIEW"; updateJob(job.id, { status: nextStatus }); setJob((current) => current ? { ...current, status: nextStatus } : current); }; void refresh(); const timer = window.setInterval(() => void refresh(), 20000); return () => { active = false; window.clearInterval(timer); }; }, [job?.id, job?.requestId]);
  async function calculateHash() { if (!uri.startsWith("https://")) return setError("Enter an HTTPS evidence URL first."); setLoading(true); setError(""); try { const response = await fetch("/api/v1/evidence", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceUrl: uri }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? payload.error ?? "Evidence snapshot failed"); setUri(`${window.location.origin}/api/v1/evidence/${payload.evidenceId}`); setHash(payload.digest); setStatus("Evidence snapshotted. The immutable commitment hash is ready."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not snapshot evidence"); } finally { setLoading(false); } }
  async function submit() { if (!job?.onChainJobId || !config.agentEscrow) return setError("This job is missing its on-chain escrow ID."); if (!/^0x[0-9a-fA-F]{64}$/.test(hash)) return setError("Calculate or enter a valid 32-byte evidence hash."); const ethereum = (window as Window & { ethereum?: { request: (args: unknown) => Promise<unknown> } }).ethereum; if (!ethereum) return setError("Connect an injected wallet to submit evidence."); setLoading(true); setError(""); try { await ethereum.request({ method: "wallet_switchEthereumChain", params: [{ chainId: "0x14a34" }] }); const wallet = createWalletClient({ chain, transport: custom(ethereum) }); const [account] = await wallet.requestAddresses(); if (!account) throw new Error("No worker wallet selected"); const tx = await wallet.writeContract({ account, address: config.agentEscrow as `0x${string}`, abi, functionName: "submitEvidence", args: [BigInt(job.onChainJobId), uri, hash as `0x${string}`] }); await createPublicClient({ chain, transport: http(config.baseRpcUrl) }).waitForTransactionReceipt({ hash: tx }); updateJob(job.id, { evidenceUri: uri, evidenceHash: hash, status: "CLAIMED" }); setJob({ ...job, evidenceUri: uri, evidenceHash: hash, status: "CLAIMED" }); setStatus("Evidence submitted. Switch to the client wallet to request review."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Evidence submission failed"); } finally { setLoading(false); } }
  async function requestReview() { if (!job?.onChainJobId || !config.agentEscrow || !config.gatewayRouter || !job.evidenceHash) return setError("Submit evidence before requesting review."); const ethereum = (window as Window & { ethereum?: { request: (args: unknown) => Promise<unknown> } }).ethereum; if (!ethereum) return setError("Connect the client wallet to request review."); setLoading(true); setError(""); try { await ethereum.request({ method: "wallet_switchEthereumChain", params: [{ chainId: "0x14a34" }] }); const wallet = createWalletClient({ chain, transport: custom(ethereum) }); const [account] = await wallet.requestAddresses(); if (!account) throw new Error("No client wallet selected"); const question = "Did the worker satisfy every mandatory requirement?"; const tx = await wallet.writeContract({ account, address: config.agentEscrow as `0x${string}`, abi, functionName: "requestVerification", args: [BigInt(job.onChainJobId), question, job.policy, BigInt(Math.floor(Date.now() / 1000) + 5 * 24 * 60 * 60)], value: parseEther(config.requestFeeEth) }); const publicClient = createPublicClient({ chain, transport: http(config.baseRpcUrl) }); const receipt = await publicClient.waitForTransactionReceipt({ hash: tx }); let requestId: `0x${string}` | undefined; for (const log of receipt.logs) { try { const decoded = decodeEventLog({ abi, data: log.data, topics: log.topics }); if (decoded.eventName === "RequestDispatched") requestId = decoded.args.requestId; } catch {} } if (!requestId) throw new Error("Request dispatched but its ID could not be read."); const state = await publicClient.readContract({ address: config.gatewayRouter as `0x${string}`, abi: routerAbi, functionName: "requests", args: [requestId] }); const response = await fetch("/api/v1/requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ requestId, requester: config.agentEscrow, originChainId: 84532, originContract: config.agentEscrow, callback: config.agentEscrow, question, policy: job.policy, evidence: { version: "1", items: [{ kind: "CONTENT_HASH", uri: job.evidenceUri, digest: job.evidenceHash, metadata: { jobId: job.onChainJobId } }] }, nonce: state[3].toString(), expiry: new Date(Number(state[4]) * 1000).toISOString(), transactionHash: tx }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Request registration failed"); updateJob(job.id, { requestId, status: "IN_REVIEW" }); setJob({ ...job, requestId, status: "IN_REVIEW" }); setStatus("Review requested. GenLayer is evaluating the evidence asynchronously."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Review request failed"); } finally { setLoading(false); } }
  if (!job) return <main className="app-page"><Link className="text-link" href="/dashboard/client"><ArrowLeft size={15} /> Back to dashboard</Link><section className="empty-state"><h1>Job not found in this browser</h1><p>Open the job from the same browser that created it, or use the on-chain job ID in the original test console.</p></section></main>;
  return <main className="app-page"><Link className="text-link" href="/dashboard/client"><ArrowLeft size={15} /> Back to dashboard</Link><div className="detail-heading"><div><span className="eyebrow">JOB {job.onChainJobId ?? job.id}</span><h1>{job.title}</h1><p>{job.description}</p></div><StatusBadge status={job.status} /></div><section className="detail-card"><ProgressRail status={job.status} /><div className="detail-columns"><div><h2>Task details</h2><dl className="detail-list"><div><dt>Bounty</dt><dd>{job.bountyEth} ETH</dd></div><div><dt>Worker</dt><dd><code>{job.worker}</code></dd></div><div><dt>Client</dt><dd><code>{job.client}</code></dd></div><div><dt>Network</dt><dd>{job.chain}</dd></div></dl></div><div><h2>What happens next?</h2><p className="muted-copy">The client funds the job. The worker submits evidence. Gateway sends the request to GenLayer, then returns the finalized decision to Base for settlement.</p>{job.requestId ? <Link className="button secondary" href={`/requests/${job.requestId}`}><ExternalLink size={15} /> View protocol trace</Link> : job.status === "CLAIMED" ? <button className="button primary" onClick={() => void requestReview()} disabled={loading}><Send size={15} /> Request GenLayer review (client wallet)</button> : <p className="muted-copy">After evidence is submitted, return to this page with the client wallet to request review.</p>}</div></div></section><section className="detail-card"><h2>Submit proof</h2><p className="muted-copy">Worker wallet action. Use a stable HTTPS URL and commit the exact response body with its keccak256 hash.</p><label className="detail-field">Evidence URL<input value={uri} onChange={(e) => setUri(e.target.value)} placeholder="https://…" /></label><button className="button ghost" onClick={() => void calculateHash()} disabled={loading}>Calculate evidence hash</button><label className="detail-field">Evidence hash<input value={hash} readOnly placeholder="0x + 64 hex" /></label><button className="button primary" onClick={() => void submit()} disabled={loading || !uri || !hash}><Send size={15} /> Submit evidence from worker wallet</button>{status && <p className="success-text" aria-live="polite">{status}</p>}{error && <p className="error-text" aria-live="assertive">{error}</p>}<ToastRegion message={status} error={error} /></section></main>;
}
